version: '3.4'

services:
  identity.sql:
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Id3ntity_2024'
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__IdentityContextConnection=${IDENTITY_DB_CONNECTION_STRING:-Server=identity.sql;Database=IdentityDb;User Id=sa;Password=Id3ntity_2024;Encrypt=False;TrustServerCertificate=true}
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro